# Generated by Django 4.1.7 on 2023-03-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloggtitle', models.CharField(max_length=100)),
                ('bloggContent', models.TextField()),
            ],
        ),
    ]
